robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB01A\WEBS\eWebReports\ \\WEB01A\d$\WEBS\eWebReports\ -w:2 /S /xo
robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB02A\WEBS\eWebReports\ \\WEB02A\d$\WEBS\eWebReports\ -w:2 /S /xo
robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB03A\WEBS\eWebReports\ \\WEB03A\d$\WEBS\eWebReports\ -w:2 /S /xo
robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB04A\WEBS\eWebReports\ \\WEB04A\d$\WEBS\eWebReports\ -w:2 /S /xo
robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB01A\WEBS\NIC_API\ \\WEB01A\d$\WEBS\NIC_API\ -w:2 /S /xo
robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB02A\WEBS\NIC_API\ \\WEB02A\d$\WEBS\NIC_API\ -w:2 /S /xo
robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB03A\WEBS\NIC_API\ \\WEB03A\d$\WEBS\NIC_API\ -w:2 /S /xo
robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB04A\WEBS\NIC_API\ \\WEB04A\d$\WEBS\NIC_API\ -w:2 /S /xo
robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB01A\WEBS\NIC\HealthCardValidationSvc\ \\WEB01A\d$\WEBS\NIC\HealthCardValidationSvc\ -w:2 /S /xo
robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB02A\WEBS\NIC\HealthCardValidationSvc\ \\WEB02A\d$\WEBS\NIC\HealthCardValidationSvc\ -w:2 /S /xo
robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB03A\WEBS\NIC\HealthCardValidationSvc\ \\WEB03A\d$\WEBS\NIC\HealthCardValidationSvc\ -w:2 /S /xo
robocopy.exe C:\CodePromotion\ProductionRelease\Deploy\FilesToDeploy\Configuration\WEB04A\WEBS\NIC\HealthCardValidationSvc\ \\WEB04A\d$\WEBS\NIC\HealthCardValidationSvc\ -w:2 /S /xo